name: Docker Image CI/CD

on:
  push:
    branches: [main]
    paths: [dkcutter.json, scripts, templates]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  check-code:
    name: Check Code - CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install

      - name: Check Code
        run: pnpm check

  generate-matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    needs: check-code
    outputs:
      versions: ${{ steps.generate.outputs.versions }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install

      - name: Generate build matrix
        run: pnpm generate-matrix
        id: generate

  build:
    name: Build Postgres ${{ matrix.postgres_version }}
    runs-on: ubuntu-latest
    needs: generate-matrix
    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      matrix:
        postgres_version: ${{ fromJSON(needs.generate-matrix.outputs.versions) }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install

      - name: Generate Dockerfile
        run: pnpm generate -y -f --postgresVersion ${{ matrix.postgres_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.postgres_version }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.postgres_version }}
