name: Integration Tests

on:
  pull_request:
    paths: ["template/**", "tests/**", dkcutter.json, versions.json]

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate-matrix.yml

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.versions) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate Dockerfile
        run: bun run generate -y -f --postgresVersion ${{ matrix.postgres_version }}

      - name: Generate Extension Template
        if: ${{ matrix.extension_template != '' }}
        run: |
          bun run generate -y -f \
            --postgresVersion ${{ matrix.postgres_version }} \
            --outputImageSlug ${{ matrix.extension_template }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build local image for testing
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ matrix.postgres_version }}
          load: true
          tags: postgres-test:${{ matrix.postgres_version }}
          cache-from: type=gha

      - name: Build local image with extension for testing
        if: ${{ matrix.extension_template != '' }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ${{ matrix.extension_template }}
          load: true
          tags: postgres-test:${{ matrix.postgres_version }}-extensions
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
            PG_APT_PACKAGES=postgresql-${{ matrix.postgres_major_version }}-postgis-3
            PG_DB_EXTENSIONS=postgis
          cache-from: type=gha

      - name: Run Integration Tests
        run: bash ./tests/test-docker.sh ${{ matrix.postgres_version }}

      - name: Run Extension Integration Tests
        if: ${{ matrix.extension_template != '' }}
        run: |
          bash ./tests/test-docker-extensions.sh \
            ${{ matrix.postgres_version }} ${{ matrix.postgres_major_version }}
